Filesystem monitor library
epam/OneDrive-L pull request #15
Opened 2017-08-17 14:05 UTC by Almost1990

2017-08-22 12:48 UTC, AndreiPashkin requested changes
I would add unit tests.

2017-08-22 12:48 UTC, AndrewPashkin commented on filesystem_service/src/filesystem_service/daemon.py
> +class Daemon(Daemonize):
This is not supposed to be here.

2017-08-22 12:48 UTC, AndrewPashkin commented on filesystem_service/src/filesystem_service/handlers.py
> +class FileSystemDbusHandler(dbus.service.Object):
Why DBus?

2017-08-23 15:36 UTC, Almost1990 commented on filesystem_service/src/filesystem_service/handlers.py
> +class FileSystemDbusHandler(dbus.service.Object):
Why not?

2017-08-24 09:32 UTC, closed without merging

2017-08-24 09:33 UTC, Almost1990 commented
Need to split into pieces